export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST"
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS"
export const ADD_PROPERTY_FAIL = "ADD_PROPERTY_FAIL"

export const LIST_PROPERTY_REQUEST = "LIST_PROPERTY_REQUEST"
export const LIST_PROPERTY_SUCCESS = "LIST_PROPERTY_SUCCESS"
export const LIST_PROPERTY_FAIL = "LIST_PROPERTY_FAIL"

export const PROPERTY_DETAILS_REQUEST = "PROPERTY_DETAILS_REQUEST"
export const PROPERTY_DETAILS_SUCCESS = "PROPERTY_DETAILS_SUCCESS"
export const PROPERTY_DETAILS_FAIL = "PROPERTY_DETAILS_FAIL"


export const LIST_USER_SPECIFIC_PROPERTY_REQUEST = "LIST_USER_SPECIFIC_PROPERTY_REQUEST"
export const LIST_USER_SPECIFIC_PROPERTY_SUCCESS = "LIST_USER_SPECIFIC_PROPERTY_SUCCESS"
export const LIST_USER_SPECIFIC_PROPERTY_FAIL = "LIST_USER_SPECIFIC_PROPERTY_FAIL"

export const SEARCH_PROPERTY_SUCCESS = "SEARCH_PROPERTY_SUCCESS"
export const SEARCH_PROPERTY_FAIL = "SEARCH_PROPERTY_FAIL"
export const SEARCH_PROPERTY_REQUEST = "SEARCH_PROPERTY_REQUEST"

export const GET_PROPERTY_TOKENS_FOR_SALE = "GET_PROPERTY_TOKENS_FOR_SALE"
export const GET_PROPERTY_TOKENS_FOR_SALE_SUCCESS = "GET_PROPERTY_TOKENS_FOR_SALE_SUCCESS"
export const GET_PROPERTY_TOKENS_FOR_SALE_FAIL = "GET_PROPERTY_TOKENS_FOR_SALE_FAIL"

export const START_AUCTION_REQUEST = "START_AUCTION_REQUEST"
export const START_AUCTION_SUCCESS = "START_AUCTION_SUCCESS"
export const START_AUCTION_FAIL = "START_AUCTION_FAIL"

export const MAKE_BID_REQUEST = "MAKE_BID_REQUEST"
export const MAKE_BID_SUCCESS = "MAKE_BID_SUCCESS"
export const MAKE_BID_FAIL = "MAKE_BID_FAIL"

export const GET_SPECIFIC_PROPERTY_REQUEST = "GET_SPECIFIC_PROPERTY_REQUEST"
export const GET_SPECIFIC_PROPERTY_SUCCESS = "GET_SPECIFIC_PROPERTY_SUCCESS"
export const GET_SPECIFIC_PROPERTY_FAIL = "GET_SPECIFIC_PROPERTY_FAIL"


export const GET_ALL_PROPERTIES_OF_SPECIFIC_USER_REQUEST = "GET_SPECIFIC_PROPERTY_REQUEST"
export const GET_ALL_PROPERTIES_OF_SPECIFIC_USER_SUCCESS = "GET_SPECIFIC_PROPERTY_SUCCESS"
export const GET_ALL_PROPERTIES_OF_SPECIFIC_USER_FAIL = "GET_SPECIFIC_PROPERTY_FAIL"